# Form implementation generated from reading ui file 'spur/resources/ui/MainWindow.ui'
#
# Created by: PyQt6 UI code generator 6.3.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1024, 768)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.canvas = Canvas(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.MinimumExpanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.canvas.sizePolicy().hasHeightForWidth())
        self.canvas.setSizePolicy(sizePolicy)
        self.canvas.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.CursorShape.ArrowCursor))
        self.canvas.setMouseTracking(False)
        self.canvas.setObjectName("canvas")
        self.horizontalLayout.addWidget(self.canvas)
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout.setObjectName("gridLayout")
        self.lineEdit = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit.setObjectName("lineEdit")
        self.gridLayout.addWidget(self.lineEdit, 0, 1, 1, 1)
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.treeWidget = QtWidgets.QTreeWidget(self.groupBox)
        self.treeWidget.setObjectName("treeWidget")
        item_0 = QtWidgets.QTreeWidgetItem(self.treeWidget)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        self.gridLayout.addWidget(self.treeWidget, 1, 1, 1, 1)
        self.horizontalLayout.addWidget(self.groupBox)
        self.verticalLayout.addLayout(self.horizontalLayout)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1024, 21))
        self.menubar.setObjectName("menubar")
        self.menuActions = QtWidgets.QMenu(self.menubar)
        self.menuActions.setObjectName("menuActions")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.action_add_component = QtGui.QAction(MainWindow)
        self.action_add_component.setObjectName("action_add_component")
        self.action_delete_component = QtGui.QAction(MainWindow)
        self.action_delete_component.setObjectName("action_delete_component")
        self.action_clone_component = QtGui.QAction(MainWindow)
        self.action_clone_component.setObjectName("action_clone_component")
        self.actionMove_Component = QtGui.QAction(MainWindow)
        self.actionMove_Component.setObjectName("actionMove_Component")
        self.menubar.addAction(self.menuActions.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Spur"))
        self.groupBox.setTitle(_translate("MainWindow", "Item Properties"))
        self.label.setText(_translate("MainWindow", "Name"))
        self.treeWidget.headerItem().setText(0, _translate("MainWindow", "Component Type"))
        __sortingEnabled = self.treeWidget.isSortingEnabled()
        self.treeWidget.setSortingEnabled(False)
        self.treeWidget.topLevelItem(0).setText(0, _translate("MainWindow", "Track Component"))
        self.treeWidget.topLevelItem(0).child(0).setText(0, _translate("MainWindow", "Timed Track"))
        self.treeWidget.topLevelItem(0).child(1).setText(0, _translate("MainWindow", "Physics Track"))
        self.treeWidget.setSortingEnabled(__sortingEnabled)
        self.menuActions.setTitle(_translate("MainWindow", "Actions"))
        self.action_add_component.setText(_translate("MainWindow", "New Component"))
        self.action_add_component.setShortcut(_translate("MainWindow", "N"))
        self.action_delete_component.setText(_translate("MainWindow", "Delete Component"))
        self.action_delete_component.setShortcut(_translate("MainWindow", "D"))
        self.action_clone_component.setText(_translate("MainWindow", "Clone Component"))
        self.action_clone_component.setShortcut(_translate("MainWindow", "C"))
        self.actionMove_Component.setText(_translate("MainWindow", "Move Component"))
from spur.gui.canvas import Canvas
